Platform.create(name: "Xbox One")
Platform.create(name: "Xbox 360")
Platform.create(name: "Playstation 4")
Platform.create(name: "Playstation 3")
Platform.create(name: "Nitendo Switch")
Platform.create(name: "Nitendo 3DS")
Platform.create(name: "Nitendo Wii")
Genre.create(name: "Action")
Genre.create(name: "RPG")
Genre.create(name: "MMO")
Genre.create(name: "FPS")
Genre.create(name: "Social simulation")
Genre.create(name: "Sandbox")
Genre.create(name: "Adventure")
Genre.create(name: "Racing")
Genre.create(name: "Fighting")
Genre.create(name: "Sport")